package org.example.modelo.enums;



public enum EnumEstadoTransaccion {
    FALTA_ENTREGARLE_EL_PRODUCTO,
    FALTA_TERMINAR_FINANCIAMIENTO,
    FALTA_PAGAR_EL_PRODUCTO,
    FALTA_REEMBOLSAR,


    TERMINO_PAGO,
    EQUIPO_ENTREGADO,
    REPARACION_TERMINADA,
    REEMBOLSO_TERMINADO,
    CAMBIO_EQUIPO_REALIZADO

}