package org.example.modelo.enums;



public enum EnumTipoTransaccion {
    COMPRA_EQUIPO, // EL CLIENTE NOS COMPRA UN EQUIPO
    REPARACION_EQUIPO,
    REEMBOLSO_EQUIPO,
    CAMBIO_EQUIPO,

    VENTA_EQUIPO,//EL CLIENTE NOS VENDE UN EQUIPO
    RESERVA_EQUIPO,

    VENTA_ACCESORIO,
    COMPRA_ACCESORIO,
    CAMBIO_ACCESORIO,
    REEMBOLSO_ACCESORIO,
}